-- https://neovim.io/doc/user/lua-guide.html#_-
--
-- See vimscript options - ed :options - vimscript


-- See lua options :h vim.
--
-- vim.g.mapleader = ","
-- 
-- vim.opt.guicursor =  ""
-- 
-- -- Where to open new windows.
-- vim.opt.splitbelow = true 
-- vim.opt.splitright = true
-- 
-- vim.opt.scrolloff = 999
-- 
-- vim.opt.number = true
-- vim.opt.relativenumber = true
-- vim.opt.tabstop = 2
-- vim.opt.shiftwidth = 2
-- vim.opt.expandtab = true
-- vim.opt.softtabstop = 2
-- 
-- vim.opt.virtualedit = "block"
-- 
-- vim.opt.smartindent = true
-- vim.opt.inccommand = "split"
-- 
-- vim.opt.ignorecase = true
-- 
-- vim.opt.wrap = false
-- 
-- vim.opt.swapfile = false
-- vim.opt.backup = false
-- vim.opt.undodir = os.getenv("HOME") .. "/.vim/undodir"
-- 
-- vim.opt.undofile = true
-- 
-- vim.opt.hlsearch = false
-- vim.opt.incsearch = true
-- 
-- 
-- vim.opt.termguicolors = true
-- vim.opt.signcolumn = "yes"
-- vim.opt.isfname:append("@-@")
-- 
-- vim.opt.updatetime = 50
-- 
-- vim.opt.colorcolumn = "80"
-- 
vim.opt.clipboard = "unnamedplus" -- unnamedplus is the default register
-- 
-- 
